version: '2'
services:

  mongo:
    image: mongo
    command: bash -c "chown -R mongodb:mongodb /data && mongod --dbpath /data/todos --oplogSize 1 --smallfiles --port 3001"
    ports:
      - "3001:3001"
    networks:
      - app
    volumes:
      - '/data/todos:/data/todos'

  todo-server:
    build:
      context: ./server
      dockerfile: "dockerfile"
    logging:
      driver: "json-file"
      options:
          max-size: "1000m"
          max-file: "10"
    ports:
        - "3005:3005"
    restart: "always"
    networks:
        - app


networks:
  app:
    driver: bridge
